### ISSUE TITLE
Add states to North America, Central America  and South America

### ISSUE THREAD

**Issue by rickygzz** [PrestaShop/LocalizationFiles#14]
# Tracking \<states> tag update
\<states> tag is used when importing States from Back Office (`International` > `Localization` > Select country on `Localization pack you want to import` > Check content to import `State` > Click `Import`)

This ticket will be used to reference all mentioned countries' xml files Pull Requests and track their approval. I will be using the ISO 3166-1 alpha-2 codes online database (https://www.iso.org/obp/ui/#iso:pub:PUB500001:en)

In the following weeks I will be creating Pulling Requests for the following

## North America

Country | Target file | Zone | Pull Request | Status | Content review
-- | -- | -- | -- | -- | -- |
Antigua & Barbuda | ag.xml | North America | | 🛑 XML file is not yet implemented. 
Bahamas | bs.xml | North America | | 🛑 XML file is not yet implemented.
Barbados | bb.xml | North America | | 🛑 XML file is not yet implemented.
Bermuda | bm.xml | North America | | 🛑 XML file is not yet implemented.
British Virgin Islands | vg.xml | North America | | 🛑 XML file is not yet implemented.
Canada | ca.xml | North America | | Verified states with ISO3166-2. Everything OK. Would move \<states> tag after \<taxes> tag for consistency, if any additional change.
Mexico | mx.xml | North America | | Work in progress. 🛠
United States | us.xml | North America | #15 | ✔ Updated. | OK

## South America

Country | Target file | Zone | Pull Request | Status | Content review
-- | -- | -- | -- | -- | --
Argentina | ar.xml | South America | #16 | 🕐 Waiting on review and approval | OK
Bolivia | bo.xml | South America | #17 | 🕐 Waiting on review and approval | OK
Brazil | br.xml | South America | | ✔ Verified states with ISO3166-2. Everything OK.
Chile | cl.xml | South America | #18 | ✔ Updated. | OK
Colombia | co.xml | South America | #19 | 🕐 Waiting on review and approval | OK
Ecuador | ec.xml | South America | #20 | ✔ Updated. | OK
French Guiana | gf.xml | South America | | 🛑 XML file is not yet implemented.
Guyana | gy.xml | South America | #25 | ✔ Updated. | OK
Paraguay | py.xml | South America | #21 | ✔ Updated. | OK
Peru | pe.xml | South America | #22 | 🕐 Waiting on review and approval | OK
Trinidad & Tobago | tt.xml | South America | | 🛑 XML file is not yet implemented.
Uruguay | uy.xml | South America | #23 | ✔ Updated. | OK
Venezuela | ve.xml | South America | #24 | ✔ Updated.  | OK

## Central America/Antilla

Country | Target file | Zone | Pull Request | Status | Content review
-- | -- | -- | -- | -- | --
Anguilla | ai.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Aruba | aw.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Belize | bz.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Cayman Islands | ky.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Costa Rica | cr.xml | Central America/Antilla | #26 | 🕐 Waiting on review and approval | OK
Cuba | cu.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Dominica | dm.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Dominican Republic | do.xml | Central America/Antilla | #27 | 🕐 Waiting on review and approval | OK
El Salvador | sv.xml | Central America/Antilla | #28 | 🕐 Waiting on review and approval | OK
Falkland Islands | fk.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Grenada | gd.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Guadeloupe | gp.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Guatemala | gt.xml | Central America/Antilla | #29 | 🕐 Waiting on review and approval | OK
Haiti | ht.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Honduras | hn.xml | Central America/Antilla | #6 | 🕐 Waiting on review and approval on PR # 6 in order to proceed adding its states (departments) | OK
Jamaica | jm.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Martinique | mq.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Montserrat | ms.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Nicaragua | ni.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Panama | pa.xml | Central America/Antilla | #30 | 🕐 Waiting on review and approval | OK
South Georgia & South Sandwich Islands | gs.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
St. Barthélemy | bl.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
St. Kitts & Nevis | kn.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
St. Lucia | lc.xml | Central America/Antilla | | 🛑  XML file is not yet implemented.
St. Martin | mf.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
St. Pierre & Miquelon | pm.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
St. Vincent & Grenadines | vc.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Suriname | sr.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.
Turks & Caicos Islands | tc.xml | Central America/Antilla | | 🛑 XML file is not yet implemented.

**Comment by rickygzz** [comment]
@PierreRambaud @Progi1984 @matks @eternoendless 

Could someone take a look at these?

**Comment by eternoendless** [comment]
Nice work @rickygzz! I think these can be accepted as long as the content is correct. These will allow users who deleted states to reinstall them again.

The core could be improved in the future to use localization packs instead of [fixtures](https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/xml/state.xml) to initialize that data during the install process.

**Comment by Julievrz** [comment]
Could someone please add the "waiting for wording" label on this issue? I can't manage to do it.

**Comment by PierreRambaud** [comment]
> Could someone please add the "waiting for wording" label on this issue? I can't manage to do it.

Done!
