### ISSUE TITLE
States with names larger than 32 characters.

### ISSUE THREAD

**Issue by rickygzz** [PrestaShop/LocalizationFiles#42]
Recently I updated us.xml localization file and it has apparently reflected its changes to prestashop.com (when user in the BO imports the localization pack from prestashop.com server).

However, the issue https://github.com/PrestaShop/PrestaShop/issues/27156 was raised. Where the state name "United States Minor Outlying Islands" was giving an error because it has more than 32 characters.

I already fixed the problem with the PR https://github.com/PrestaShop/PrestaShop/pull/27162 allowing 64 characters instead of 32 for State names.

But, I am afraid that all the users with current 1.7.8.2 and previous versions of PS who download the localization pack data from the server won´t be able to add the States.

![image](https://user-images.githubusercontent.com/36200981/147842184-fa0876e5-87db-4431-83dc-d4214b09735b.png)

Should we enforce users to wait for the next PS stable release?

We could also update `us.xml` file and rename "United States Minor Outlying Islands" to "Minor Outlying Islands" which goes from 36 to 22 characters. It will fix the problem with previous versions, but it won´t match with ISO 3166-2 names.

If we leave the us.xml as it is right now, the users will get the error, but the other US states will be installed inside ps_state table.

**Comment by eternoendless** [comment]
Unfortunately we'll have to truncate the names to 32 characters to avoid breaking all shops 😬
